# Generated by Django 4.2.5 on 2023-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productfeatures_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
